ReviewMetadata.create!(field_name: "cleanliness")
ReviewMetadata.create!(field_name: "pests")
ReviewMetadata.create!(field_name: "sunlight")
ReviewMetadata.create!(field_name: "convenience")
ReviewMetadata.create!(field_name: "noise_level")
ReviewMetadata.create!(field_name: "ceilings")
ReviewMetadata.create!(field_name: "closet_space")
ReviewMetadata.create!(field_name: "intercom_system")
ReviewMetadata.create!(field_name: "temp_control")
ReviewMetadata.create!(field_name: "appliances")
ReviewMetadata.create!(field_name: "countertops")
ReviewMetadata.create!(field_name: "floors")
ReviewMetadata.create!(field_name: "bathrooms")
ReviewMetadata.create!(field_name: "walls")
ReviewMetadata.create!(field_name: "utilities")
ReviewMetadata.create!(field_name: "neighbors")
ReviewMetadata.create!(field_name: "laundry")
ReviewMetadata.create!(field_name: "mass_transit")
ReviewMetadata.create!(field_name: "neighborhood")
ReviewMetadata.create!(field_name: "storage")
ReviewMetadata.create!(field_name: "packages")
ReviewMetadata.create!(field_name: "super")

#Neighborhoods
Neighborhood.create!(name: "Morningside Heights")
Neighborhood.create!(name: "Harlem")
Neighborhood.create!(name: "East Harlem")
Neighborhood.create!(name: "Upper West Side")
Neighborhood.create!(name: "Upper East Side")
Neighborhood.create!(name: "Midtown West")
Neighborhood.create!(name: "Midtown East")
Neighborhood.create!(name: "Times Square")
Neighborhood.create!(name: "Garment District")
Neighborhood.create!(name: "Murray Hill")
Neighborhood.create!(name: "Chelsea")
Neighborhood.create!(name: "Gramercy")
Neighborhood.create!(name: "Stuyvesant Town")
Neighborhood.create!(name: "Greenwich Village")
Neighborhood.create!(name: "West Vilalge")
Neighborhood.create!(name: "East Village")
Neighborhood.create!(name: "Soho")
Neighborhood.create!(name: "Little Italy")
Neighborhood.create!(name: "Lower East Side")
Neighborhood.create!(name: "Chinatown")
Neighborhood.create!(name: "Tribeca")
Neighborhood.create!(name: "Financial District")
